# Generated by Django 4.1.5 on 2023-02-06 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_workout_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='workout date')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('effort', models.CharField(choices=[('*', '1 Star'), ('**', '2 Star'), ('***', '3 Star'), ('****', '4 Star'), ('*****', '5 Star')], default='*', max_length=5, verbose_name='effort given')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.workout')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
