# Generated by Django 4.1.6 on 2023-02-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logging',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='loggings',
            field=models.ManyToManyField(to='main_app.logging'),
        ),
    ]
