# Generated by Django 4.1.5 on 2023-02-09 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_logging_workout_workout_loggings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='loggings',
        ),
        migrations.AddField(
            model_name='logging',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.workout'),
            preserve_default=False,
        ),
    ]
